api/Dockerfile

Added the copy command to the Dockerfile.

fixing api dockerfile

---

api/src/pools/subscription-pools/index.test.ts
api/src/pools/subscription-pools/index.ts
api/src/routes/channel/index.test.ts
api/src/routes/router.ts
api/src/services/channel-service.ts
api/src/services/streams-service.ts
api/src/services/subscription-service.ts

- remove old objects from subscriber or author array to prevent a overflow

39 dynamic subscription pool

---

api/src/database/trusted-roots.ts
api/src/models/schemas/request-body/verification-bodies.ts
api/src/models/types/request-bodies.ts
api/src/routes/channel-info/index.ts
api/src/routes/identity/index.ts
api/src/routes/router.ts
api/src/routes/verification/index.ts
api/src/routes/verification/tests/trusted-roots.test.ts
api/src/services/authorization-service.ts
api/src/services/verification-service.ts

- possibility to add a trusted root as admin
- possibility to remove a trusted root as admin

127 maintainable trusted roots

---

api/src/database/verifiable-credentials.ts
api/src/routers/authentication/index.ts
api/src/routers/channel-info/index.ts
api/src/routers/channel/index.ts
api/src/routers/identity/index.ts
api/src/routers/middlewares.ts
api/src/routers/services.ts
api/src/routers/subscription/index.ts
api/src/routers/verification/index.ts
api/src/routes/identity/index.test.ts
api/src/routes/identity/index.ts
api/src/services/verification-service.ts

- remove user specific details in credentials when it gets deleted

154 gdpr compliance

---

api/src/routers/services.ts
api/src/routes/channel/tests/index.test.ts
api/src/routes/channel/tests/reimport.test.ts
api/src/routes/channel/tests/validate.test.ts
api/src/services/channel-service.ts
api/src/services/streams-service.ts
api/src/utils/channel-log-transformer/index.ts

fetch messages from tangle and compare them with the payload

22 finalize validate data

---

.github/workflows/deploy-e-shop-backend.yml
clients/e-shop-demo/e-shop-backend/vercel.json
clients/e-shop-demo/e-shop-frontend/vercel.json

- `vercel.json` for e-shop-backend
- `vercel.json` for e-shop-frontend (muting github comments)
- pipeline for deployment to vercel for the backend

Vercel integration for e-shop

---

documentation/.gitignore
documentation/EXTERNAL_DOCS_CONFIG
documentation/EXTERNAL_DOCS_DROPDOWN_CONFIG
documentation/README.md
documentation/config.json
documentation/docs/welcome.md
documentation/package-lock.json
documentation/package.json
documentation/sidebars.js

- Added docusarus through `iota-wiki-cli`
- Documentation Enhancement
Changes were tested locally.

Docs - Added docusaurus through iota-wiki-cli

---

api/src/services/streams-service.ts

Used a more cryptographically secure random generator

#293: removed Math.random() 

---

.github/workflows/test-docs-wiki-build.yml

- Updated action name 
- Added manual workflow dispatch
- Enhancement (a non-breaking change which adds functionality)

Updated action name

---

api/src/setup/database-seeder.ts
clients/cbc/device/src/config/config.ts
clients/frama-c-client/log-auditor/src/config/index.ts
clients/frama-c-client/log-creator/src/config/index.ts
clients/tm-forum/csp1-bss/src/config/config.ts
clients/tm-forum/lead-csp/src/config/config.ts

Before you are able to run the setup-api script you need to make sure all your usernames in the database are unique.

341 fix unique username field

---

api/src/middlewares/mongodb-sanitizer.test.ts
api/src/middlewares/mongodb-sanitizer.ts
api/src/routers/authentication/index.ts
api/src/routers/channel-info/index.ts
api/src/routers/channel/index.ts
api/src/routers/identity/index.ts
api/src/routers/subscription/index.ts
api/src/routers/verification/index.ts

Added middleware which checks if a key starts with $ to prevent possible mongodb injections.

351 prevent mongodb injection

---

documentation/docs/welcome.md

Re-added a welcome banner provided by @DuncanMain . 
- Enhancement (a non-breaking change which adds functionality)
- Documentation Enhancement
Wiki was built locally

Docs - Re Added welcome banner

---

api/src/routers/identity/index.ts
api/src/routes/identity/index.test.ts
api/src/routes/identity/index.ts
clients/node/examples/0-MakeRootIdentityAdmin.ts
clients/node/examples/1-CreateIdentityAndCredential.ts
clients/node/examples/2-UpdateUser.ts
clients/node/examples/3-DeleteUser.ts
clients/node/examples/4-TrustedAuthorities.ts
clients/node/examples/5-CreateChannel.ts
clients/node/examples/6-AuthorizeToChannel.ts
clients/node/examples/7-SearchChannelAndValidateData.ts

- add warning for duplicated username
- adjust examples to always generate unique username when creating an identity
- fix docs error

420 fix username problem

---

clients/e-shop-demo/e-shop-backend/.env-example
clients/e-shop-demo/e-shop-backend/package-lock.json
clients/e-shop-demo/e-shop-frontend/src/app.tsx
clients/e-shop-demo/e-shop-frontend/src/components/checkout-iota/checkout-iota.component.tsx
clients/e-shop-demo/e-shop-frontend/src/components/checkout-item/checkout-item.component.tsx
clients/e-shop-demo/e-shop-frontend/src/components/generate-nonce/generate-nonce.component.tsx
clients/e-shop-demo/e-shop-frontend/src/components/switch-tour/switch-tour.component.tsx
clients/e-shop-demo/e-shop-frontend/src/components/switch-tour/switch-tour.styles.tsx
clients/e-shop-demo/e-shop-frontend/src/components/tour/tour.component.tsx
clients/e-shop-demo/e-shop-frontend/src/contexts/cart.provider.tsx
clients/e-shop-demo/e-shop-frontend/src/contexts/tour.provider.tsx
clients/e-shop-demo/e-shop-frontend/src/pages/checkout/checkout.component.tsx

- Added toggle to turn off tour
- Fixed bug when deleting cart items

fixed bug with checkout items, added toggle for tour

---

clients/cbc/postman-requests.postman_collection.json
clients/node/examples/README.md
documentation/docs/examples/how-to-run-examples.mdx
documentation/docs/getting_started/installation/docker_compose/docker_compose.md
documentation/docs/getting_started/installation/kubernetes/configuration.md
documentation/docs/getting_started/installation/kubernetes/local_setup.md
documentation/docs/getting_started/installation/kubernetes/rest.txt
documentation/docs/getting_started/installation/nodejs/local_setup.md
documentation/docs/welcome.md
kubernetes/is-config.yaml
kubernetes/is-secrets.yaml
kubernetes/optional/mongo-deployment.yaml
kubernetes/optional/mongo-init-config.yaml

* Updated API_KEY and SERVER_SECRET in both docs and code.
* Added warning in welcome.md
Wiki was built locally.

Update API_KEY and SERVER_SECRET 

---

documentation/docs/api_reference.md

* Changed links for Audit  Trail and SSI bridge
Wiki was built locally

Docs - Update Audit Trail and SSI Bridge links

---

documentation/docs/getting_started/installation/docker_compose/docker_compose.md

I installed the API with docker compose twice and those are things I stumbled upon during installation

Docker compose setup update

---

api/shared-modules/package.json
clients/client-sdk/README.md
clients/client-sdk/examples/.env.example
clients/client-sdk/examples/configuration.ts
clients/client-sdk/package.json
documentation/docs/examples/authorize-to-channel.md
documentation/docs/examples/create-channel.md
documentation/docs/examples/create-identity-and-credentials.mdx
documentation/docs/examples/delete-users.md
documentation/docs/examples/how-to-run-examples.mdx
documentation/docs/examples/introduction.mdx
documentation/docs/examples/search-channel-and-validate-data.md
documentation/docs/examples/trusted-authorities.md
documentation/docs/examples/update-users.md

- **Important** fix for is-client npm package
- Documentation update
- Added examples to NPM readme

Wiki adjustments new client

---

documentation/docs/welcome.md

* Added bug reporting admonition
* Added severity to personal data admoniton
* 
https://github.com/iotaledger/integration-services/issues/491
Choose a type of change, and delete any options that are not relevant.
- Enhancement (a non-breaking change which adds functionality)
Wiki was built locally.

* Added bug reporting admonition

---

api/ssi-bridge/package-lock.json
api/ssi-bridge/src/routers/authentication/index.ts
api/ssi-bridge/src/routers/services.ts
api/ssi-bridge/src/routes/authentication/index.test.ts
api/ssi-bridge/src/routes/authentication/index.ts
api/ssi-bridge/src/services/authentication-service.ts
api/ssi-bridge/src/services/ssi-service.ts
clients/client-sdk/package-lock.json
clients/client-sdk/package.json
clients/client-sdk/src/clients/identity.ts
clients/client-sdk/src/models/index.ts
clients/client-sdk/tsconfig.json

509 jwt validation

---

clients/client-sdk/package-lock.json
clients/client-sdk/package.json
clients/client-sdk/src/clients/base.ts
clients/client-sdk/src/clients/channel.ts
clients/client-sdk/src/clients/identity.ts
clients/client-sdk/src/models/clientConfig.ts
clients/client-sdk/src/tests/channel.test.ts
clients/client-sdk/src/tests/test.data.ts

- add option to have empty isGatewayUrl

Allow empty gateway url

---

dashboard/package-lock.json
dashboard/package.json
dashboard/src/routes/__layout.svelte
dashboard/src/routes/history/[channelAddress].svelte
dashboard/src/routes/history/index.svelte

- add support for channel history

549 integrate public channel dashboard

---

clients/client-sdk/package-lock.json
clients/client-sdk/package.json
clients/client-sdk/src/clients/identity.ts
dashboard/package-lock.json
dashboard/package.json
dashboard/svelte.config.js

Changed configuration in svelte to run in container without refresh problem, in production mode

Fix dashboard refresh problem

---

clients/client-sdk/examples/.env.example
clients/client-sdk/examples/configuration.ts
clients/client-sdk/examples/package-lock.json
clients/client-sdk/examples/package.json

make use_gate_url customizable

make use_gate_url customizable

---

documentation/docs/services/dashboard/dashboard.md
documentation/docs/services/dashboard/ui-components.md
documentation/sidebars.js

**PLEASE MERGE PR 8 before**
- Added UI components page to the wiki (mostly contents of the ui components README)
- Added folder containing the integration services dashboard and the ui components

7 add is UI components to wiki

---

api/ssi-bridge/src/services/authentication-service.ts

- only add relevant content to the jwt

reduce jwt overhead

---

.gitignore
api/audit-trail-gw/package-lock.json
api/audit-trail-gw/package.json
api/audit-trail-gw/src/index.ts
api/audit-trail-gw/src/middlewares/metrics.ts
api/ssi-bridge/package-lock.json
api/ssi-bridge/package.json
api/ssi-bridge/src/index.ts
api/ssi-bridge/src/middlewares/metrics.ts

- Added monitoring middlewares to audit-trail and ssi-bridge
- Expose metrics with `/metrics` endpoint
closes #260

260 monitoring split services

---

api/audit-trail-gw/CHANGELOG.md
api/audit-trail-gw/package-lock.json
api/audit-trail-gw/package.json
api/shared-modules/CHANGELOG.md
api/shared-modules/package-lock.json
api/shared-modules/package.json
api/ssi-bridge/CHANGELOG.md
api/ssi-bridge/package-lock.json
api/ssi-bridge/package.json
clients/client-sdk/CHANGELOG.md
clients/client-sdk/README.md
clients/client-sdk/package-lock.json
clients/client-sdk/package.json
clients/client-sdk/src/clients/channel.ts
clients/client-sdk/src/tests/channel.test.ts
clients/client-sdk/tools/deleteLines.js
dashboard/package-lock.json
dashboard/package.json

- Updated dependencies and fixed audit vulnerabilities for **ssi-bridge**, **audit-trail** and **client-sdk**
- Added changelog files for APIs and client
- Small adjustments in **client-sdk** needed because of updated dependencies

62 fix dependencies
